kind: Deployment
apiVersion: apps/v1
metadata:
  name: order-server
  namespace: default
  labels:
    k8s-app: order-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: order-server
  template:
    metadata:
      name: order-server
      labels:
        k8s-app: order-server
    spec:
      containers:
        - name: order-server
          image: http-proxy-playground/order:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Djava.net.preferIPv4Stack=true -Dvertx.disableDnsResolver=true"
            - name: POSTGRES_SERVER_HOST
              value: "$(POSTGRES_SERVICE_SERVICE_HOST)"
            - name: POSTGRES_SERVER_PORT
              value: "$(POSTGRES_SERVICE_SERVICE_PORT)"
---
kind: Service
apiVersion: v1
metadata:
  name: order-service
  namespace: default
  labels:
    k8s-app: order-service
spec:
  type: ClusterIP
  selector:
    k8s-app: order-server
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
