kind: Service
apiVersion: v1
metadata:
  name: delivery-service
  namespace: default
  labels:
    k8s-app: delivery-service
spec:
  type: ClusterIP
  selector:
    k8s-app: delivery-server
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
