kind: Deployment
apiVersion: apps/v1
metadata:
  name: edge-server
  namespace: default
  labels:
    k8s-app: edge-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: edge-server
  template:
    metadata:
      name: edge-server
      labels:
        k8s-app: edge-server
    spec:
      containers:
        - name: edge-server
          image: http-proxy-playground/edge:latest
          imagePullPolicy: Never
          env:
            - name: PRODUCT_SERVER_HOST
              value: "$(PRODUCT_SERVICE_SERVICE_HOST)"
            - name: PRODUCT_SERVER_PORT
              value: "$(PRODUCT_SERVICE_SERVICE_PORT)"
            - name: ORDER_SERVER_HOST
              value: "$(ORDER_SERVICE_SERVICE_HOST)"
            - name: ORDER_SERVER_PORT
              value: "$(ORDER_SERVICE_SERVICE_PORT)"
            - name: DELIVERY_SERVER_HOST
              value: "$(DELIVERY_SERVICE_SERVICE_HOST)"
            - name: DELIVERY_SERVER_PORT
              value: "$(DELIVERY_SERVICE_SERVICE_PORT)"
