kind: Deployment
apiVersion: apps/v1
metadata:
  name: product-server
  namespace: default
  labels:
    k8s-app: product-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: product-server
  template:
    metadata:
      name: product-server
      labels:
        k8s-app: product-server
    spec:
      containers:
        - name: product-server
          image: http-proxy-playground/product:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Djava.net.preferIPv4Stack=true -Dvertx.disableDnsResolver=true"
---
kind: Service
apiVersion: v1
metadata:
  name: product-service
  namespace: default
  labels:
    k8s-app: product-service
spec:
  type: ClusterIP
  selector:
    k8s-app: product-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
